version: '3.8'
services:
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stone_dev
    network_mode: host
    volumes:
      - ~/data/pocs/stone/db:/var/lib/postgresql/data