version: '3.8'
services:
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stone_dev
    network_mode: host
    volumes:
      - ~/data/pocs/stone/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  tweteroo-csharp:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: tweteroo-csharp
    environment:
      - DATABASE__HOST=localhost
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=postgres
      - DATABASE__NAME=stone_dev
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
