on:
  push:
    branches:
      - main

name: Build and Deploy to Cloud Run
env:
  PK: ${{ secrets.AWS_PK }}
  DEPLOY_USER: ${{ secrets.AWS_DEPLOY_USER }}
  DEPLOY_HOST: ${{ secrets.AWS_DEPLOY_HOST }}
  DEPLOY_PATH: ${{ secrets.AWS_DEPLOY_PATH }}
  TAR_PATH: ${{ secrets.AWS_TAR_PATH }}
  TMP_DIR: ${{ secrets.AWS_TMP_DIR }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: STAGING
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Application
        run: bash ./.deploy/build.sh

      - name: Build Migrations
        run: bash ./.deploy/build_migrations.sh

      - name: Push to EC2
        run: bash ./.deploy/push.sh

      - name: Deploy And Run Migrations
        run: ssh -i /tmp/pk.pem $DEPLOY_USER@$DEPLOY_HOST "bash git pull && bash $DEPLOY_PATH/deploy.sh"