on:
  push:
    branches:
      - main

name: Build and Deploy to AWS EC2
env:
  PK: ${{ secrets.AWS_PK }}
  DEPLOY_USER: ${{ secrets.AWS_DEPLOY_USER }}
  DEPLOY_HOST: ${{ secrets.AWS_DEPLOY_HOST }}
  DEPLOY_PATH: ${{ secrets.AWS_DEPLOY_PATH }}
  TAR_PATH: ${{ secrets.AWS_TAR_PATH }}
  TMP_DIR: ${{ secrets.AWS_TMP_DIR }}
  DATABASE_URL: ${{ secrets.AWS_DATABASE_URL }}
  PK_PATH: /tmp/pk

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: STAGING
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Application
        run: bash ./.deploy/build.sh

      - name: Build Migrations
        run: bash ./.deploy/build_migrations.sh

      - name: Store SSH Key
        run: bash ./.deploy/store_ssh_key.sh

      - name: Push to EC2
        run: bash ./.deploy/push.sh

      - name: Deploy And Run Migrations
        run: ssh -o StrictHostKeyChecking=no -i /tmp/pk $DEPLOY_USER@$DEPLOY_HOST "export TAR_PATH=${TAR_PATH} && export DEPLOY_PATH=${DEPLOY_PATH} && cd $DEPLOY_PATH && git pull && bash ./.deploy/deploy.sh"
